### ISSUE TITLE
ge:used replacement

### ISSUE THREAD

**Issue by thvitt** [faustedition/xml#606]
- `<mod>` is not allowed between zones #595 
- `<modSpan>` is not part of current TEI
I guess this is sth like [`<metamark function="used"/>`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-metamark.html)? What do you think @gerritbruening?

**Comment by gerritbruening** [comment]
You are right: @TEIC decided not to adopt `ge:used` from the genetic draft. Instead, they recommended `<metamark function="used"/>` for that purpose.
My memory says that there was a discussion on the council mailing list in 2011 or so. Can you, @brettttt, help and serve as contemporary witness?
Anyway, I think `<metamark function="used"/>` would be canonic albeit odd, since something is struck out. This would be recorded with `mod` if it didn't happen to occur outside `line` elements.

**Comment by thvitt** [comment]
what to do now? Decision required … if metamark is ok, you may close this issue, otherwise decide on some encoding please before assigning me again

**Comment by gerritbruening** [comment]
Ah okay, then I'll close it. I thought that there would be something left to do for someone (and that you are that someone).
It makes me dizzy to see that our encoding will make a time travel from 2010/11 to 2018, or, as someone famlously put it, "Es schwindelt."
